version: '3'
services:
  oh-eth:
    links:
    - postgres:postgres  
    env_file: .npmrc.dev
  postgres:
    image: postgres
    ports:
    - "5432:5432"
    container_name: postgres
    env_file:
    - ./.npmrc.dev    